# This file may be used to create an environment using:
#   $ conda create --name <env> --file <this file>
# platform: linux-64
name: py27
channels:
 - conda-forge
 - defaults
dependencies:
 - python=2.7.18
 - pyrosim=0.1.1=dev_0
 - pip=19.3.1
 - nose=1.3.7
 - numpy=1.16.6
 - matplotlib=2.2.3